### ISSUE TITLE
ERROR  - nil value local Player

### ISSUE THREAD

**Issue by xCoryux** [Hiype/hiype-cardelivery#10]
Good,

Every so often I see that on the server I get this error:

`SCRIPT ERROR: @ Hiype-cardelivery / server.lua: 56: attempt to index a nil value (local 'Player')`

Sometimes it happens to me when I stay in the multicharacter and don't select anyone. At the time this error appears.

**Comment by PETER-PARKER69** [comment]
Yes mee to getting this any fix uave

**Comment by Hiype** [comment]
This error should not break anything in this script, I will fix it but it's not on my priority list at the moment.

**Comment by Hiype** [comment]
Should be fixed in the rewrite version.
