### ISSUE TITLE
Suggestion: Add a real police requirement.

### ISSUE THREAD

**Issue by Martinator9001** [Hiype/hiype-cardelivery#13]
Adding a real police count requirement of the mission assignor spawning (or you being able to start the mission from the ped) could be useful, since in RP servers there can be only real police as police, so if there isn't any online then people could farm the robbery.

**Comment by Hiype** [comment]
Oh, that's a great idea! I will implement that.

**Comment by Hiype** [comment]
The latest commit has this feature added!
