### ISSUE TITLE
Cluster of Peds

### ISSUE THREAD

**Issue by ChurchTG7** [Hiype/hiype-cardelivery#19]
![image](https://user-images.githubusercontent.com/48700200/178163839-179cf4d4-3230-494c-9447-394401ffee4c.png)
Cluster of peds fresh install with metadata in core

**Comment by Hiype** [comment]
I know of this problem, but I'm currently very busy with other things, will fix this when I'm able to.

**Comment by Deadgaminglive** [comment]
fixed yet?

**Comment by Hiype** [comment]
Nope

**Comment by Hiype** [comment]
Could be fixed, please test it if you can.
