### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by MrAladin-afs** [Hiype/hiype-cardelivery#21]
**Describe the bug**
Target not working

[fixed]

**Comment by MrAladin-afs** [comment]
not fully fixed after join target not woking but after join i need to restart the script then it will be works

**Comment by snapcupcake** [comment]
Have you fixed it?

**Comment by MrAladin-afs** [comment]
no i need fix:(

**Comment by Hiype** [comment]
I will try to recreate this problem this evening.

**Comment by MrAladin-afs** [comment]
ok broo

**Comment by Hiype** [comment]
Please check out this new build, I think i fixed it!

**Comment by MrAladin-afs** [comment]
okk bro
