### ISSUE TITLE
Suggestion: locales

### ISSUE THREAD

**Issue by xCoryux** [Hiype/hiype-cardelivery#6]
It would be interesting if all the text shown to the user is in a local. Either directly in the config or the separate files. I say this because those of us who use another language, every time you make an update, we always have to translate.

**Comment by Hiype** [comment]
I will work on this! Can't say how soon, but either at the end of this week or early next week a new commit should come.

> It would be interesting if all the text shown to the user is in a local. Either directly in the config or the separate files. I say this because those of us who use another language, every time you make an update, we always have to translate.

**Comment by Hiype** [comment]
@xCoryux The latest commit should be what you were suggesting I hope!
