### ISSUE TITLE
Issue with blips

### ISSUE THREAD

**Issue by aphrohoo** [Hiype/hiype-cardelivery#7]
I'm currently running the newest QBCore, love the concept btw. I'm having an issue where the job starts, but the next objective doesn't show on the map. I'm trying to go through the code a bit and normally I can solve it but this one has stumped me. Can you provide some help as to why it might not be showing? I basically just copy pasted your folder into the server and added the required line. I'm getting no errors so it's hard to troubleshoot.

**Comment by Hiype** [comment]
@aphrohoo I've had this problem only on OneSync, not sure how to fix it yet, but i will try to fix this next week!

**Comment by aphrohoo** [comment]
I'm not sure if OneSync is secretly active on my server but I attempted to turn it off and am still encountering the bug. I await the fix and will let you know if I find a solution (:

**Comment by Hiype** [comment]
I hope the latest commit fixed this problem...hopefully.
