### ISSUE TITLE
Fresh install nil issues

### ISSUE THREAD

**Issue by SovietRulez** [Hiype/hiype-cardelivery#8]
https://i.imgur.com/GtVlKRQ.png = https://i.imgur.com/1NxhgRe.png
https://i.imgur.com/w6iZ3ZE.png = https://i.imgur.com/ZL3MAor.png

**Comment by Hiype** [comment]
I will look into this!

> https://i.imgur.com/GtVlKRQ.png = https://i.imgur.com/1NxhgRe.png https://i.imgur.com/w6iZ3ZE.png = https://i.imgur.com/ZL3MAor.png

**Comment by BrandsPickled** [comment]
Any updates on this, I have the issue.

**Comment by Hiype** [comment]
> Any updates on this, I have the issue.

Not yet, currently working on it. If I'm not busy, i might be done with this some time next week!

**Comment by Hiype** [comment]
Any script braking problems should be fixed in the latest commit! :)
